git:
  depth: 1

language: node_js
node_js:
  - "8"

install: npm install

env:
  - SELENIDEJS_REMOTE_URL="http://217.73.84.220:4444/wd/hub"

script: npm run build

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"